/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'bpant' at '17/5/17 6:33 PM' with Gradle 2.4
 *
 * @author bpant, @date 17/5/17 6:33 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
