/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'bpant' at '17/5/17 6:33 PM' with Gradle 2.4
 *
 * @author bpant, @date 17/5/17 6:33 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
